# run.sub -- simple job
# execute with condor_submit condor/nb-run.sub

executable              = condor/run.sh
arguments               = /data/rjfgroup/rjf01/cameron.parker/builds/Bayes-Tune/full-tune.ipynb

log                     = condor/run.log
output                  = condor/run.out
error                   = condor/run.err

request_cpus            = 1
batch_name              = stat-run
getenv                  = True

queue